apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: campaigner
commonLabels:
  app.kubernetes.io/name: campaigner-web
  app.kubernetes.io/part-of: campaigner
resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - secret.example.yaml
  - ingress.yaml
images:
  - name: us-central1-docker.pkg.dev/bemtech-478413/generic-agent-repo/campaigner-web
    newTag: latest
