apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: campaigner
resources:
  - ../../base
patches:
  - path: patch-deployment.yaml
    target: { kind: Deployment, name: campaigner-web }
  - path: patch-ingress.yaml
    target: { kind: Ingress, name: campaigner-web }
images:
  - name: us-central1-docker.pkg.dev/bemtech-478413/generic-agent-repo/campaigner-web
    newTag: stable
