"""
tools/compose_monthly_report.py — structured monthly client deliverable
(Mastery v2 Phase G, 2026-05-17).

Composes the report skeleton per Mastery v2 §1.8 (agency-grade structure):

  cover           — business name, month, period dates
  exec_summary    — 3-sentence verdict / cause / action (agent-generated)
  kpi_scorecard   — 1-3 KPIs vs target (quality-adjusted CPL leads when divergent)
  mom_yoy         — month-over-month + YoY on headline KPI
  decisions_log   — what we did this month (approvals filtered to non-observation)
  insights        — O-I-R triplets (observation → insight → recommendation)
  next_month_plan — proposed test hypotheses + budget shifts (seed for monthly_brief)
  asks_from_op    — what we need from operator (lead grading, creative inputs, budget OK)
  agent_funnel    — proposed/approved/rejected/why (transparency, no human agency can do this)

Output: structured JSON the /reports/[month] page renders into RTL Hebrew.
The narrative-Hebrew strings (exec_summary, insights[].recommendation,
next_month_plan paragraphs) are generated by Claude separately — this tool
provides the SHAPE + the numeric inputs.

Contract: §11.6 (JSON stdout, exit 0/1/2).
"""

from __future__ import annotations

import argparse
from datetime import UTC, date, datetime, timedelta

from campaigner.lib.config import Config, ConfigError
from campaigner.lib.db import fetch_all, fetch_one
from campaigner.tools._contract import (
    emit_runtime_error,
    emit_success,
    emit_validation_error,
    with_db_retry,
)


def _month_bounds(month_yyyymm: str) -> tuple[date, date]:
    """Parse YYYY-MM → (first day, last day) of that month."""
    y, m = month_yyyymm.split("-")
    first = date(int(y), int(m), 1)
    if int(m) == 12:
        next_first = date(int(y) + 1, 1, 1)
    else:
        next_first = date(int(y), int(m) + 1, 1)
    last = next_first - timedelta(days=1)
    return first, last


def main() -> None:
    p = argparse.ArgumentParser(
        description="Compose structured monthly report inputs for /reports/[month] page.",
    )
    p.add_argument("--business-id", required=True)
    p.add_argument("--month", required=True, help="YYYY-MM (e.g. 2026-05)")
    args = p.parse_args()

    try:
        first, last = _month_bounds(args.month)
    except (ValueError, IndexError):
        emit_validation_error(f"--month must be YYYY-MM, got {args.month!r}")
        return

    try:
        Config.load().require_db()
    except ConfigError as e:
        emit_validation_error(str(e))
        return

    try:
        biz = with_db_retry(
            lambda: fetch_one(
                """
                SELECT id, name, monthly_budget_ils, primary_kpi,
                       target_cpa_ils, target_cpl_ils, target_roas
                  FROM businesses WHERE id = %s
                """,
                (args.business_id,),
            )
        )
    except Exception as e:
        emit_runtime_error(f"business query failed: {e}", exc=e)
        return
    if not biz:
        emit_validation_error(f"business {args.business_id} not found")
        return

    # Approvals during the month — split into "what we did" (executed) and
    # "what we proposed" (pending/answered/approved-not-executed).
    try:
        approvals = with_db_retry(
            lambda: fetch_all(
                """
                SELECT id, task_type, status, urgency, rationale,
                       created_at, executed_at, approved_at,
                       rejection_reason
                  FROM approvals
                 WHERE business_id = %s
                   AND created_at::date BETWEEN %s AND %s
                """,
                (args.business_id, first, last),
            )
        )
    except Exception as e:
        emit_runtime_error(f"approvals query failed: {e}", exc=e)
        return

    executed = [a for a in approvals if a["status"] == "executed"]
    approved_pending_exec = [a for a in approvals if a["status"] == "approved"]
    rejected = [a for a in approvals if a["status"] == "rejected"]
    answered = [a for a in approvals if a["status"] == "answered"]
    pending = [a for a in approvals if a["status"] == "pending"]
    total = len(approvals)

    # Rejection theme aggregation (simple: top 3 by count)
    reject_themes: dict[str, int] = {}
    for r in rejected:
        reason = (r.get("rejection_reason") or "").strip()
        if not reason:
            continue
        # Truncate to first 80 chars as theme proxy
        key = reason[:80]
        reject_themes[key] = reject_themes.get(key, 0) + 1
    top_rejects = sorted(reject_themes.items(), key=lambda kv: -kv[1])[:3]

    # Lead-quality summary for the month
    try:
        lq = with_db_retry(
            lambda: fetch_one(
                """
                SELECT count(*) AS leads_count,
                       sum(CASE WHEN g.grade IS NOT NULL THEN 1 ELSE 0 END) AS graded_count,
                       avg(g.grade) AS avg_grade,
                       sum(CASE WHEN g.converted THEN 1 ELSE 0 END) AS converted_count,
                       sum(CASE WHEN g.converted THEN g.converted_value_ils ELSE 0 END) AS revenue_ils
                  FROM leads l
             LEFT JOIN lead_latest_grade g ON g.lead_id = l.id
                 WHERE l.business_id = %s
                   AND l.meta_created_at::date BETWEEN %s AND %s
                """,
                (args.business_id, first, last),
            )
        )
    except Exception:
        lq = None
        # Tolerate — lead-quality may not be wired yet (Phase C dependency)
    leads_count = (lq or {}).get("leads_count") or 0
    graded_count = (lq or {}).get("graded_count") or 0
    avg_grade = (lq or {}).get("avg_grade")
    converted_count = (lq or {}).get("converted_count") or 0
    revenue_ils = (lq or {}).get("revenue_ils") or 0

    grading_coverage = graded_count / leads_count if leads_count > 0 else None

    # Latest budget_health snapshot for the month
    try:
        bh = with_db_retry(
            lambda: fetch_one(
                """
                SELECT outputs
                  FROM agent_decisions
                 WHERE business_id = %s
                   AND graph_name = 'observe_propose'
                   AND node_name = 'budget_health'
                   AND created_at::date BETWEEN %s AND %s
                 ORDER BY created_at DESC
                 LIMIT 1
                """,
                (args.business_id, first, last),
            )
        )
    except Exception:
        bh = None
    bh_outputs = (bh or {}).get("outputs") or {}

    report = {
        "cover": {
            "business_id": args.business_id,
            "business_name": biz["name"],
            "month": args.month,
            "period_start": first.isoformat(),
            "period_end": last.isoformat(),
            "generated_at": datetime.now(UTC).isoformat(),
        },
        "kpi_scorecard": {
            "primary_kpi": biz.get("primary_kpi"),
            "target": (
                biz.get("target_cpl_ils")
                if biz.get("primary_kpi") == "cpl"
                else biz.get("target_cpa_ils")
                if biz.get("primary_kpi") == "cpa"
                else biz.get("target_roas")
            ),
            "leads_count": leads_count,
            "graded_count": graded_count,
            "grading_coverage": (
                round(grading_coverage, 3) if grading_coverage is not None else None
            ),
            "avg_quality_grade": (round(float(avg_grade), 2) if avg_grade is not None else None),
            "converted_count": converted_count,
            "revenue_ils": float(revenue_ils),
        },
        "budget": {
            "monthly_budget_ils": biz.get("monthly_budget_ils"),
            "effective_monthly_budget": bh_outputs.get("effective_monthly_budget"),
            "spend_this_month": bh_outputs.get("spend_this_month"),
            "pace": bh_outputs.get("pace"),
            "status": bh_outputs.get("status"),
            "seasonal_multiplier": bh_outputs.get("seasonal_multiplier"),
        },
        "decisions_log": [
            {
                "approval_id": str(a["id"]),
                "task_type": a["task_type"],
                "executed_at": (a["executed_at"].isoformat() if a.get("executed_at") else None),
                "rationale_first_paragraph": (a.get("rationale") or "")[:300],
            }
            for a in executed[:20]
        ],
        "agent_funnel": {
            "total_proposed": total,
            "executed": len(executed),
            "approved_pending_exec": len(approved_pending_exec),
            "answered": len(answered),
            "rejected": len(rejected),
            "pending": len(pending),
            "approval_rate": (
                round((len(executed) + len(approved_pending_exec)) / total, 3)
                if total > 0
                else None
            ),
            "top_rejection_themes": [{"theme": k, "count": v} for k, v in top_rejects],
        },
        "asks_from_operator": _compute_asks(
            grading_coverage=grading_coverage,
            pending_count=len(pending),
            answered_count=len(answered),
            biz=biz,
        ),
        # The narrative sections (exec_summary, insights[].recommendation,
        # next_month_plan) are generated by Claude via a separate composer
        # call — this tool provides the numeric scaffolding only.
        "narrative_placeholders": {
            "exec_summary": None,
            "insights": [],
            "next_month_plan": None,
        },
    }

    emit_success(report)


def _compute_asks(
    grading_coverage: float | None,
    pending_count: int,
    answered_count: int,
    biz: dict,
) -> list[dict]:
    """The Asks-From-Operator block. Concrete, actionable items the operator
    needs to do for next month to succeed.
    """
    asks: list[dict] = []
    if grading_coverage is not None and grading_coverage < 0.6:
        asks.append(
            {
                "priority": "high",
                "ask_he": (
                    f"דירוג איכות לידים — סך כיסוי "
                    f"{int(grading_coverage * 100)}% (יעד: 60%+). "
                    f"גש ל-/leads ודרג את הלידים הממתינים."
                ),
                "action_url": "/leads",
            }
        )
    if pending_count >= 5:
        asks.append(
            {
                "priority": "high",
                "ask_he": (f"יש {pending_count} הצעות ממתינות. עבור עליהן ב-/approvals."),
                "action_url": "/approvals",
            }
        )
    if answered_count > 0:
        asks.append(
            {
                "priority": "medium",
                "ask_he": (
                    f"ענית על {answered_count} שאלות MCQ — הסוכן יקרא אותן "
                    f"ברצף הבא ויחזור עם הצעה מעודנת."
                ),
                "action_url": "/approvals",
            }
        )
    if biz.get("primary_kpi") is None:
        asks.append(
            {
                "priority": "high",
                "ask_he": (
                    "יעד KPI ראשי לא מוגדר. בלי יעד אין למה להשוות. הגדר ב-/business-knowledge."
                ),
                "action_url": "/business-knowledge",
            }
        )
    if not biz.get("monthly_budget_ils"):
        asks.append(
            {
                "priority": "high",
                "ask_he": (
                    "תקציב חודשי לא מוגדר — לא ניתן לעקוב אחרי קצב או "
                    "להחליט על scale_up. הגדר ב-/business-knowledge."
                ),
                "action_url": "/business-knowledge",
            }
        )
    return asks


if __name__ == "__main__":
    main()
