#!/usr/bin/env python3
"""Generate cronjob manifests and prompt-load matrices from config/flows.yaml.

`config/flows.yaml` is the single source of truth for the campaigner flow
registry. This script regenerates the artifacts derived from it:

    - kubefiles/agent_cronjob_<cronjob_name>.yaml  (one per deployed cron flow)
    - The "Which flow am I running?" routing table in campaigner/CAMPAIGNER.md
    - The "Before every flow — Load context" matrix in CAMPAIGNER.md
    - The flow index table in docs/ARCHITECTURE.md

Run modes:

    python scripts/generate_from_flows.py            # write
    python scripts/generate_from_flows.py --check    # exit 1 on drift (CI)

The --check mode does not modify any files. It computes what the output
would be and compares against what is on disk. Drift means a hand-edit
slipped past review; rerun without --check to fix.
"""

from __future__ import annotations

import argparse
import difflib
import re
import sys
from dataclasses import dataclass
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
FLOWS_YAML = REPO_ROOT / "config" / "flows.yaml"
KUBEFILES_DIR = REPO_ROOT / "kubefiles"
CAMPAIGNER_MD = REPO_ROOT / "campaigner" / "CAMPAIGNER.md"
ARCHITECTURE_MD = REPO_ROOT / "docs" / "ARCHITECTURE.md"

# Sentinel pairs that fence generated regions. Hand-edits between these
# markers are overwritten on the next `make generate`.
SENTINEL_ROUTING = "flows:routing-table"
SENTINEL_MATRIX = "flows:prompt-load-matrix"
SENTINEL_FLOW_INDEX = "flows:flow-index"

CRONJOB_TEMPLATE = """\
# Flow {flow_id} — {description_short}{schedule_comment}
# Generated by scripts/generate_from_flows.py from config/flows.yaml — do not edit by hand.
apiVersion: batch/v1
kind: CronJob
metadata:
  name: agent-{cronjob_name}
  namespace: {namespace}
spec:
  schedule: "{schedule}"
  timeZone: "{timezone}"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: {starting_deadline}
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: {active_deadline}
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: agent
              image: {image}
              imagePullPolicy: Always
              command: ["bash", "{runner}"]
              envFrom:
                - secretRef:
                    name: campaigner-secrets
              env:
                - name: GCP_PROJECT_ID
                  value: "{gcp_project}"
                - name: GCP_LOCATION
                  value: "{gcp_location}"
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: "{gcp_creds_path}"
              volumeMounts:
                - name: gcp-credentials
                  mountPath: /var/secrets/gcp
                  readOnly: true
              resources:
                requests: {{ cpu: {req_cpu}, memory: {req_mem} }}
                limits: {{ cpu: {lim_cpu}, memory: {lim_mem} }}
          volumes:
            - name: gcp-credentials
              secret:
                secretName: gcp-vertexai-credentials
"""


@dataclass
class Flow:
    id: str
    name: str
    label: str
    description: str
    schedule: str | None
    schedule_human: str
    runner: str
    trigger_signals: list[str]
    section_anchor: str
    section_label: str
    deployed: bool
    cronjob_name: str | None
    deadlines: dict | None
    resources: dict | None
    prompts_always: list[str]
    prompts_on_demand: list[str]


def load_registry() -> tuple[dict, dict, list[Flow]]:
    raw = yaml.safe_load(FLOWS_YAML.read_text())
    defaults = raw["defaults"]
    prompts = raw["prompts"]
    flows: list[Flow] = []
    for entry in raw["flows"]:
        flows.append(
            Flow(
                id=entry["id"],
                name=entry["name"],
                label=entry["label"],
                description=entry["description"],
                schedule=entry.get("schedule"),
                schedule_human=entry["schedule_human"],
                runner=entry["runner"],
                trigger_signals=entry["trigger_signals"],
                section_anchor=entry["section_anchor"],
                section_label=entry["section_label"],
                deployed=entry["deployed"],
                cronjob_name=entry.get("cronjob_name"),
                deadlines=entry.get("deadlines"),
                resources=entry.get("resources"),
                prompts_always=list(entry["prompts"]["always"]),
                prompts_on_demand=list(entry["prompts"]["on_demand"]),
            )
        )
    return defaults, prompts, flows


def render_cronjob(flow: Flow, defaults: dict) -> str:
    if not flow.deployed or flow.schedule is None:
        return ""
    schedule_comment = f" {flow.schedule_human}." if flow.schedule_human else ""
    description_short = flow.label.replace("-", " ").capitalize() + "."
    if flow.id == "B":
        description_short = "Execute approvals."
    env = defaults["env"]
    return CRONJOB_TEMPLATE.format(
        flow_id=flow.id,
        description_short=description_short,
        schedule_comment=schedule_comment,
        cronjob_name=flow.cronjob_name,
        namespace=defaults["namespace"],
        schedule=flow.schedule,
        timezone=defaults["timezone"],
        starting_deadline=flow.deadlines["starting_seconds"],
        active_deadline=flow.deadlines["active_seconds"],
        image=defaults["image"],
        runner=flow.runner,
        gcp_project=env["GCP_PROJECT_ID"],
        gcp_location=env["GCP_LOCATION"],
        gcp_creds_path=env["GOOGLE_APPLICATION_CREDENTIALS"],
        req_cpu=flow.resources["requests"]["cpu"],
        req_mem=flow.resources["requests"]["memory"],
        lim_cpu=flow.resources["limits"]["cpu"],
        lim_mem=flow.resources["limits"]["memory"],
    )


def render_routing_table(flows: list[Flow]) -> str:
    lines = [
        "| Signal in prompt | Flow | Schedule |",
        "| --- | --- | --- |",
    ]
    for f in flows:
        signals = " / ".join(f'"{s}"' for s in f.trigger_signals)
        flow_link = f"[{f.section_label}](#{f.section_anchor})"
        lines.append(f"| {signals} | {flow_link} | {f.schedule_human} |")
    lines.append('| "onboard business" | manual CLI (not cron) | operator-initiated |')
    return "\n".join(lines)


def render_prompt_matrix(flows: list[Flow], prompts: dict) -> str:
    # Column order matches flow id order (A..H).
    headers = ["Prompt"] + [f"{f.id}: {f.label}" for f in flows]
    sep = ["---"] * len(headers)
    lines = ["| " + " | ".join(headers) + " |", "|" + "|".join(sep) + "|"]

    # Row order matches the catalog order in flows.yaml.
    for prompt_id, prompt_path in prompts.items():
        row = [f"[`{Path(prompt_path).name}`]({Path(prompt_path).relative_to('campaigner')})"]
        for f in flows:
            if prompt_id in f.prompts_always:
                row.append("✅")
            elif prompt_id in f.prompts_on_demand:
                row.append("on-demand*")
            else:
                row.append("—")
        lines.append("| " + " | ".join(row) + " |")
    return "\n".join(lines)


def render_flow_index(flows: list[Flow]) -> str:
    lines = [
        "| Flow | Name | Schedule | Touches Meta? | Runner |",
        "| --- | --- | --- | --- | --- |",
    ]
    for f in flows:
        touches_meta = "Yes (writes)" if f.id == "B" else "No"
        lines.append(
            f"| **{f.id}** | {f.name} | {f.schedule_human} | {touches_meta} | "
            f"[`{f.runner}`](../{f.runner}) |"
        )
    return "\n".join(lines)


def replace_between_sentinels(text: str, sentinel: str, new_body: str) -> str:
    """Replace content between `<!-- BEGIN GENERATED:<sentinel> -->` and
    `<!-- END GENERATED:<sentinel> -->` markers.

    Raises if either marker is missing — sentinels must be added manually
    once; the generator owns the contents between them thereafter.
    """
    begin = f"<!-- BEGIN GENERATED:{sentinel} -->"
    end = f"<!-- END GENERATED:{sentinel} -->"
    pattern = re.compile(
        re.escape(begin) + r".*?" + re.escape(end),
        flags=re.DOTALL,
    )
    if not pattern.search(text):
        raise SystemExit(
            f"ERROR: sentinel pair '{sentinel}' not found.\n"
            f"  Expected: {begin} ... {end}\n"
            f"  Add the markers to the target file once; the generator "
            f"replaces everything between them."
        )
    replacement = f"{begin}\n{new_body}\n{end}"
    return pattern.sub(replacement, text)


def planned_outputs() -> dict[Path, str]:
    """Return {path: content} for every file the generator owns."""
    defaults, prompts, flows = load_registry()
    outputs: dict[Path, str] = {}

    # CronJob manifests — one per deployed cron flow. The filename uses the
    # cronjob_name (with hyphens replaced by underscores) to match the
    # existing convention: `agent-daily-observe` -> `agent_cronjob_daily_observe.yaml`.
    for f in flows:
        if not f.deployed or f.schedule is None:
            continue
        filename = f"agent_cronjob_{f.cronjob_name.replace('-', '_')}.yaml"
        path = KUBEFILES_DIR / filename
        outputs[path] = render_cronjob(f, defaults)

    # CAMPAIGNER.md — routing table + prompt-load matrix.
    campaigner_text = CAMPAIGNER_MD.read_text()
    campaigner_text = replace_between_sentinels(
        campaigner_text, SENTINEL_ROUTING, render_routing_table(flows)
    )
    campaigner_text = replace_between_sentinels(
        campaigner_text, SENTINEL_MATRIX, render_prompt_matrix(flows, prompts)
    )
    outputs[CAMPAIGNER_MD] = campaigner_text

    # ARCHITECTURE.md — flow index.
    arch_text = ARCHITECTURE_MD.read_text()
    arch_text = replace_between_sentinels(arch_text, SENTINEL_FLOW_INDEX, render_flow_index(flows))
    outputs[ARCHITECTURE_MD] = arch_text

    return outputs


def find_orphan_cronjobs(expected: set[Path]) -> list[Path]:
    """Cronjob YAMLs that exist on disk but are not produced by the generator.

    Anything matching `kubefiles/agent_cronjob_*.yaml` is owned by this
    generator. A file that doesn't correspond to a flow in flows.yaml is
    an orphan — usually a rename or a deleted flow.
    """
    on_disk = set(KUBEFILES_DIR.glob("agent_cronjob_*.yaml"))
    return sorted(on_disk - expected)


def write_mode() -> int:
    outputs = planned_outputs()
    changed: list[Path] = []
    for path, content in outputs.items():
        existing = path.read_text() if path.exists() else None
        if existing != content:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
            changed.append(path)

    cronjob_paths = {p for p in outputs if p.parent == KUBEFILES_DIR}
    orphans = find_orphan_cronjobs(cronjob_paths)
    for path in orphans:
        path.unlink()
        changed.append(path)

    if changed:
        print(f"Wrote/removed {len(changed)} file(s):")
        for p in changed:
            marker = "(removed orphan)" if p in orphans else ""
            print(f"  {p.relative_to(REPO_ROOT)} {marker}".rstrip())
    else:
        print("Already up to date.")
    return 0


def check_mode() -> int:
    outputs = planned_outputs()
    drift: list[tuple[Path, str]] = []
    for path, content in outputs.items():
        existing = path.read_text() if path.exists() else ""
        if existing != content:
            diff = "\n".join(
                difflib.unified_diff(
                    existing.splitlines(),
                    content.splitlines(),
                    fromfile=f"a/{path.relative_to(REPO_ROOT)}",
                    tofile=f"b/{path.relative_to(REPO_ROOT)}",
                    lineterm="",
                )
            )
            drift.append((path, diff))

    cronjob_paths = {p for p in outputs if p.parent == KUBEFILES_DIR}
    orphans = find_orphan_cronjobs(cronjob_paths)

    if drift or orphans:
        if drift:
            print("DRIFT — generated files are out of sync with config/flows.yaml:")
            for path, diff in drift:
                print(f"\n--- {path.relative_to(REPO_ROOT)} ---")
                print(diff)
        if orphans:
            print("\nORPHAN cronjob manifests (no matching entry in flows.yaml):")
            for p in orphans:
                print(f"  {p.relative_to(REPO_ROOT)}")
        print(
            "\nRun `make generate` to regenerate, then commit the result.\n"
            "If the change is intentional, edit config/flows.yaml first — "
            "hand-edits to generated files are rejected at review.",
        )
        return 1
    print("OK — generated files match config/flows.yaml.")
    return 0


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify generated files are in sync; exit 1 on drift. Used in CI.",
    )
    args = parser.parse_args(argv)
    if args.check:
        return check_mode()
    return write_mode()


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
