"""Generated from config/thresholds.yaml — do not edit by hand.

This module exposes the tunable rule thresholds the agent's prompts
reference as `{{<domain>.<name>}}` placeholders. The schema version is
stamped on every `agent_decisions` row by `log_decision.py`, so any past
run's decisions can be re-evaluated against the threshold snapshot that
was loaded for them.

Regenerate by editing `config/thresholds.yaml` and running
`make generate`. CI's `make verify-generated` rejects drift.
"""

from __future__ import annotations

SCHEMA_VERSION = "1.0.0"


# anti_flood
ANTI_FLOOD_BUDGET_TIER_SMALL_ILS = 50
ANTI_FLOOD_BUDGET_TIER_MEDIUM_ILS = 500
ANTI_FLOOD_MAX_PROPOSALS_SMALL = 2
ANTI_FLOOD_MAX_PROPOSALS_MEDIUM = 5
ANTI_FLOOD_MAX_PROPOSALS_LARGE = 10

# gate_1
GATE_1_HOOK_RATE_GOOD_PCT = 35
GATE_1_HOOK_RATE_KILL_PCT = 25
GATE_1_CTR_GOOD_PCT = 2
GATE_1_CTR_KILL_PCT = 1
GATE_1_THUMBSTOP_GOOD_PCT = 30
GATE_1_THUMBSTOP_KILL_PCT = 20
GATE_1_IMPRESSIONS_FLOOR = 1000
GATE_1_CLICKS_FLOOR = 50
GATE_1_EVALUATION_WINDOW_HOURS = 48

# gate_2
GATE_2_WINNER_RATIO = 0.85
GATE_2_BASELINE_BAND_PCT = 15
GATE_2_EXPENSIVE_THRESHOLD = 1.3
GATE_2_EMERGENCY_THRESHOLD = 3.0
GATE_2_EXPENSIVE_SUSTAINED_DAYS = 5
GATE_2_EMERGENCY_ZERO_CONV_DAYS = 3
GATE_2_FATIGUE_CPR_MULTIPLE = 2.0
GATE_2_AB_TEST_SIGNIFICANCE_PCT = 95

# learning
LEARNING_MIN_CONVERSIONS_FOR_EXIT = 50
LEARNING_MAX_DAYS_BEFORE_LIMITED = 7

# utilization
UTILIZATION_SEVERELY_UNDER_CEILING = 0.5
UTILIZATION_UNDER_CEILING = 0.8
UTILIZATION_HEALTHY_CEILING = 1.05
UTILIZATION_NEW_CREATIVE_FLOOR = 0.5

# scaling
SCALING_SCALE_UP_BRANCH_A_PCT = 30
SCALING_SCALE_UP_BRANCH_B_PCT = 20
SCALING_SCALE_UP_BRANCH_C_PCT = 15
SCALING_SCALE_UP_DEFAULT_CAP_PCT = 20
SCALING_SCALE_UP_STRICT_CAP_PCT = 30
SCALING_SCALE_DOWN_STEP_PCT = 15
SCALING_COOLDOWN_HOURS = 72
SCALING_CADENCE_WINDOW_DAYS = 7
SCALING_MARGINAL_RETURN_MIN_LIFT = 1.1
SCALING_MARGINAL_RETURN_LOOKBACK_DAYS = 14
SCALING_CONSECUTIVE_SCALE_DOWN_WINDOW_DAYS = 14

# ab_test
AB_TEST_MIN_VARIANTS = 2
AB_TEST_MAX_VARIANTS = 4
AB_TEST_MIN_WINDOW_DAYS = 7

# solid_strong
SOLID_STRONG_UTIL_FLOOR = 0.95
SOLID_STRONG_FREQ_CEILING = 2.5
SOLID_STRONG_HOOK_FLOOR = 0.3

# portfolio
PORTFOLIO_SAFETY_CAP_ILS = 200
PORTFOLIO_DELTA_FLOOR_ILS = 10

# feedback
FEEDBACK_PRIOR_REJECTION_LOOKBACK_DAYS = 60
FEEDBACK_ACTIVE_PLAN_WINDOW_DAYS = 21
