#!/usr/bin/env bash
# runners/onboarding_chain.sh
#
# Flow F — Onboarding (Mastery v2 Phase A, 2026-05-17). Runs after Meta OAuth
# completes for a business, walks the operator through brief → audience →
# scan → first campaign proposal in one orchestration.
#
# Triggered by:
#   - OAuth handler post-success (web → /api/runners/trigger?flow=onboarding)
#   - Or operator manually via `campaigner run onboarding`
#
# Idempotent: each step checks the business's `onboarding_status` and skips
# steps already done. Safe to re-run if it crashed mid-flow.
#
# Status transitions per step:
#   not_started → brief_pending          (after propose_business_brief)
#   brief_pending → audience_brief_pending (after operator fills brief)
#   audience_brief_pending → scanning    (after audience_brief is answered)
#   scanning → first_proposal_pending    (after scan tools complete)
#   first_proposal_pending → completed   (after first_campaign approval lands)
#
# Exit codes:
#   0 — success (one step advanced OR nothing to do)
#   1 — runtime failure
#   2 — env / args validation failure
#
# Note: this runner does NOT call `claude -p`. The chain logic is fully
# deterministic — there's no judgment call needed for "what's the next step."
# Each step's content (the rationale, the brief layout, the first-campaign
# numbers) IS generated by the tools, but the orchestration is shell.

set -euo pipefail

FLOW="onboarding_chain"
START_TS=$(date +%s%3N)

: "${BUSINESS_ID:?BUSINESS_ID must be set}"

cd "$(dirname "$0")/.."

python -m campaigner.tools.heartbeat \
  --business-id "$BUSINESS_ID" \
  --flow "$FLOW" \
  --phase start >/dev/null

on_error() {
  local exit_code=$?
  local duration=$(($(date +%s%3N) - START_TS))
  python -m campaigner.tools.heartbeat \
    --business-id "$BUSINESS_ID" \
    --flow "$FLOW" \
    --phase error \
    --exit-code "$exit_code" \
    --duration-ms "$duration" \
    --error-message "onboarding_chain exited non-zero" || true
  exit "$exit_code"
}
trap on_error ERR

RUN_ID=$(python -c "import uuid; print(uuid.uuid4())")
PSQL_QUERY() {
  python -c "
import sys
from campaigner.lib.db import fetch_one
row = fetch_one('SELECT onboarding_status FROM businesses WHERE id = %s', ('$BUSINESS_ID',))
print(row['onboarding_status'] if row else 'unknown')
"
}

STATUS=$(PSQL_QUERY)
echo "onboarding_chain: business=$BUSINESS_ID status=$STATUS"

advance_status() {
  local new_status="$1"
  python -c "
from campaigner.lib.db import execute
execute('UPDATE businesses SET onboarding_status = %s WHERE id = %s', ('$new_status', '$BUSINESS_ID'))
"
}

case "$STATUS" in
  not_started)
    python -m campaigner.tools.propose_business_brief \
      --business-id "$BUSINESS_ID" --run-id "$RUN_ID"
    advance_status brief_pending
    ;;
  brief_pending)
    # Check if the business brief has been filled (business_knowledge row
    # exists with at least products + service_regions set). If yes, advance.
    FILLED=$(python -c "
from campaigner.lib.db import fetch_one
row = fetch_one('SELECT products, service_regions FROM business_knowledge WHERE business_id = %s', ('$BUSINESS_ID',))
print('yes' if row and row.get('products') and row.get('service_regions') else 'no')
")
    if [[ "$FILLED" == "yes" ]]; then
      python -m campaigner.tools.propose_audience_brief \
        --business-id "$BUSINESS_ID" --run-id "$RUN_ID"
      advance_status audience_brief_pending
    else
      echo "Brief still pending — operator hasn't filled /business-knowledge yet. No-op."
    fi
    ;;
  audience_brief_pending)
    # Check if the audience_brief approval has been answered (status='answered'
    # or 'approved'). If yes, advance to scanning.
    ANSWERED=$(python -c "
from campaigner.lib.db import fetch_one
row = fetch_one(\"SELECT count(*) AS n FROM approvals WHERE business_id = %s AND task_type = 'audience_brief' AND status IN ('answered', 'approved')\", ('$BUSINESS_ID',))
print('yes' if row and (row.get('n') or 0) > 0 else 'no')
")
    if [[ "$ANSWERED" == "yes" ]]; then
      advance_status scanning
      # Fall through to scanning below
      STATUS=scanning
    else
      echo "Audience brief still pending — operator hasn't answered yet. No-op."
    fi
    ;;
esac

# Scanning phase: run gallery backfill + health checks + alignment, then
# transition to first_proposal_pending.
if [[ "$STATUS" == "scanning" ]]; then
  echo "Running scan: backfill_gallery + check_account_health + check_business_alignment + check_tracking_health"
  python -m campaigner.tools.backfill_gallery_from_meta --business-id "$BUSINESS_ID" || true
  python -m campaigner.tools.check_account_health --business-id "$BUSINESS_ID" || true
  python -m campaigner.tools.check_business_alignment --business-id "$BUSINESS_ID" || true
  python -m campaigner.tools.check_tracking_health --business-id "$BUSINESS_ID" || true

  python -m campaigner.tools.propose_first_campaign \
    --business-id "$BUSINESS_ID" --run-id "$RUN_ID"
  advance_status first_proposal_pending
fi

# first_proposal_pending → completed transition fires when the first_campaign
# approval is approved/answered. That's handled by an /api/approvals callback
# OR by the daily Flow A run noticing the approval status.

DURATION=$(($(date +%s%3N) - START_TS))
python -m campaigner.tools.heartbeat \
  --business-id "$BUSINESS_ID" \
  --flow "$FLOW" \
  --phase end \
  --duration-ms "$DURATION" \
  --exit-code 0 >/dev/null

echo "✓ $FLOW step completed for status=$STATUS (now: $(PSQL_QUERY)) in ${DURATION}ms"
